### ISSUE TITLE
Installation instructions missing?

### ISSUE THREAD

**Issue by chezhouse** [chris1869/freeciv-bot#4]
The current civ_prep_selnium.sh file did not correctly access the geckodriver url when downloading through curl.  This can be fixed by supplying a more recent link to the 0.27.0 version.

However, as far as I can tell, there is no **build_freeciv_server** command present within the repository.
Is this an implied command for creating a freeciv-web server, or is there supposed to be a specific command available?

**Comment by chris1869** [comment]
The repo is now updated - please check if your problem is now resolved.
